### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by arBalasquide** [ros-melodic-arch/ros-melodic-topic-tools#2]
/usr/bin/ld: warning: libboost_thread.so.1.69.0, needed by /opt/ros/melodic/lib/libroscpp.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libboost_chrono.so.1.69.0, needed by /opt/ros/melodic/lib/libroscpp.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libboost_filesystem.so.1.69.0, needed by /opt/ros/melodic/lib/libroscpp.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libboost_regex.so.1.69.0, needed by /opt/ros/melodic/lib/librosconsole.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /opt/ros/melodic/lib/librosconsole.so: undefined reference to `boost::re_detail_106900::verify_options(unsigned int, boost::regex_constants::_match_flags)'
/usr/bin/ld: /opt/ros/melodic/lib/librosconsole.so: undefined reference to `boost::re_detail_106900::raise_runtime_error(std::runtime_error const&)'
/usr/bin/ld: /opt/ros/melodic/lib/librosconsole.so: undefined reference to `boost::re_detail_106900::put_mem_block(void*)'
/usr/bin/ld: /opt/ros/melodic/lib/libroscpp.so: undefined reference to `boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool)'
/usr/bin/ld: /opt/ros/melodic/lib/librosconsole.so: undefined reference to `boost::re_detail_106900::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
/usr/bin/ld: /opt/ros/melodic/lib/librosconsole.so: undefined reference to `boost::re_detail_106900::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
/usr/bin/ld: /opt/ros/melodic/lib/librosconsole.so: undefined reference to `boost::re_detail_106900::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
/usr/bin/ld: /opt/ros/melodic/lib/librosconsole.so: undefined reference to `boost::re_detail_106900::get_default_error_string(boost::regex_constants::error_type)'
/usr/bin/ld: /opt/ros/melodic/lib/librosconsole.so: undefined reference to `boost::re_detail_106900::get_mem_block()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/switch_mux.dir/build.make:103: devel/lib/topic_tools/switch_mux] Error 1
make[1]: *** [CMakeFiles/Makefile2:1090: CMakeFiles/switch_mux.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().

Its trying to use boost1.69 lib files, but the package update requires the use of boost1.71. I'm assuming this happens to other packages for ros-melodic-* , but theres 80 more packages to be updated so I don't really have the time to check them one by one. 

Would something like --nodeps be a workaround for this?

**Comment by jwhendy** [comment]
Sadly, we are all feeling this pain at the moment :( For example [here](https://github.com/ros-melodic-arch/ros-melodic-rosbag/issues/1) and [here](https://github.com/ros-melodic-arch/ros-melodic-tf2-ros/issues/2).

For some hope: I rebuilt all of `ros-melodic-{ros-base, desktop, desktop-full, moveit}` over the weekend and everything works. The down side is that the linking seems non-trivial. I've rebuilt ros-melodic-warehouse-ros fin (so updated to boost 1.71), then gone to build another package which complains that ros-melodic-warehouse-ros depends on a non-existent 1.69 boost lib. I believe this is because the deps of ros-melodic-warehouse-ros were still linked, but somehow that didn't come up when building. I gave up, removed all my ros-melodic-* packages and started over, building from scratch.

While I empathize, your errors are for other packages (roscpp, rosconsole) and I also just build this package locally to make sure, so I'm closing this.
